In [1]:
import pandas as pd
import numpy as np

In [2]:
book = pd.read_csv(
    "data.csv",
    encoding="latin-1",
    engine="python",
    on_bad_lines="skip"
)

In [3]:
book.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   str
 2   title           6810 non-null   str
 3   subtitle        2381 non-null   str
 4   authors         6738 non-null   str
 5   categories      6711 non-null   str
 6   thumbnail       6481 non-null   str
 7   description     6548 non-null   str
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), str(7)
memory usage: 4.3 MB

In [4]:
print(book.columns)

Index(['isbn13', 'isbn10', 'title', 'subtitle', 'authors', 'categories',
       'thumbnail', 'description', 'published_year', 'average_rating',
       'num_pages', 'ratings_count'],
      dtype='str')

In [5]:
df = book[[ 'title', 'authors', 'categories','published_year']]

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           6810 non-null   str
 1   authors         6738 non-null   str
 2   categories      6711 non-null   str
 3   published_year  6804 non-null   float64
dtypes: float64(1), str(3)
memory usage: 549.1 KB

In [7]:
df

,title,authors,categories,published_year
0,Gilead,Marilynne Robinson,Fiction,2004.0
1,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,2000.0
2,The One Tree,Stephen R. Donaldson,American fiction,1982.0
3,Rage of angels,Sidney Sheldon,Fiction,1993.0
4,The Four Loves,Clive Staples Lewis,Christian life,2002.0
...,...,...,...,...
6805,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,1999.0
6806,Secrets Of The Heart,Khalil Gibran,Mysticism,1993.0
6807,Fahrenheit 451,Ray Bradbury,Book burning,2004.0
6808,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,1981.0
6809,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,1998.0

In [8]:
df = df.iloc[:2000]

In [9]:
print(df.shape)

(2000, 4)

In [11]:
# Change the datatype of published_year 
df["published_year"] = pd.to_numeric(df["published_year"], errors = 'coerce')   
df.dropna(subset=["published_year"], inplace = True )    # Drop the null data  
df["published_year"] = df["published_year"].astype(int)          #converted the data into integer formate

In [12]:
 df.fillna(" ", inplace = True)

,title,authors,categories,published_year
0,Gilead,Marilynne Robinson,Fiction,2004
1,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,2000
2,The One Tree,Stephen R. Donaldson,American fiction,1982
3,Rage of angels,Sidney Sheldon,Fiction,1993
4,The Four Loves,Clive Staples Lewis,Christian life,2002
...,...,...,...,...
1995,Dr. Desirable,Kristi Gold,Fiction,2002
1996,Blame it on the Blackout,Heidi Betts,Fiction,2005
1997,Bedded Then Wed,Heidi Betts,Fiction,2006
1998,Blackmailed Into Bed,Heidi Betts,Fiction,2007
1999,Tell Me No Lies,Elizabeth Lowell,Fiction,2006

In [13]:
#Create the function that is used to make the text in lowercase , remove stop words , remove punctiontion
df.columns

Index(['title', 'authors', 'categories', 'published_year'], dtype='str')

In [14]:
df.duplicated().value_counts()   #Check duplicate values

False    1997
Name: count, dtype: int64

In [15]:
# to remove space in between words 
#df['title'] = df['title'].str.replace(' ' ,'_')
df['authors'] = df['authors'].str.replace(' ' ,'_')
df['categories'] = df['categories'].str.replace(' ' ,'_')

In [16]:
# inserted the column of ID so that proper indexing the data will get 
df.insert(0, "ID", range(1, len(df) + 1))

In [17]:
df

,ID,title,authors,categories,published_year
0,1,Gilead,Marilynne_Robinson,Fiction,2004
1,2,Spider's Web,Charles_Osborne;Agatha_Christie,Detective_and_mystery_stories,2000
2,3,The One Tree,Stephen_R._Donaldson,American_fiction,1982
3,4,Rage of angels,Sidney_Sheldon,Fiction,1993
4,5,The Four Loves,Clive_Staples_Lewis,Christian_life,2002
...,...,...,...,...,...
1995,1993,Dr. Desirable,Kristi_Gold,Fiction,2002
1996,1994,Blame it on the Blackout,Heidi_Betts,Fiction,2005
1997,1995,Bedded Then Wed,Heidi_Betts,Fiction,2006
1998,1996,Blackmailed Into Bed,Heidi_Betts,Fiction,2007
1999,1997,Tell Me No Lies,Elizabeth_Lowell,Fiction,2006

In [18]:
df['tags'] = (
    df['authors'] + ',' +
    df['categories'] + ',' +
    df['published_year'].astype(str)
)

In [19]:
df['tags']

0                         Marilynne_Robinson,Fiction,2004
1       Charles_Osborne;Agatha_Christie,Detective_and_...
2              Stephen_R._Donaldson,American_fiction,1982
3                             Sidney_Sheldon,Fiction,1993
4                 Clive_Staples_Lewis,Christian_life,2002
                              ...
1995                             Kristi_Gold,Fiction,2002
1996                             Heidi_Betts,Fiction,2005
1997                             Heidi_Betts,Fiction,2006
1998                             Heidi_Betts,Fiction,2007
1999                        Elizabeth_Lowell,Fiction,2006
Name: tags, Length: 1997, dtype: str

In [20]:
df.columns

Index(['ID', 'title', 'authors', 'categories', 'published_year', 'tags'], dtype='str')

In [21]:
df =df[['ID', 'title',  'tags']]

In [22]:
df.head()

   ID           title                                               tags
0   1          Gilead                    Marilynne_Robinson,Fiction,2004
1   2    Spider's Web  Charles_Osborne;Agatha_Christie,Detective_and_...
2   3    The One Tree         Stephen_R._Donaldson,American_fiction,1982
3   4  Rage of angels                        Sidney_Sheldon,Fiction,1993
4   5  The Four Loves            Clive_Staples_Lewis,Christian_life,2002

In [23]:
df['tags']= df['tags'].str.lower()    # convert everything in to lowercase

In [24]:
df['tags'] = df['tags'].str.replace('.' ,'')

In [25]:
df.to_csv("cleaned_data.csv")

In [26]:
df

,ID,title,tags
0,1,Gilead,"marilynne_robinson,fiction,2004"
1,2,Spider's Web,"charles_osborne;agatha_christie,detective_and_..."
2,3,The One Tree,"stephen_r_donaldson,american_fiction,1982"
3,4,Rage of angels,"sidney_sheldon,fiction,1993"
4,5,The Four Loves,"clive_staples_lewis,christian_life,2002"
...,...,...,...
1995,1993,Dr. Desirable,"kristi_gold,fiction,2002"
1996,1994,Blame it on the Blackout,"heidi_betts,fiction,2005"
1997,1995,Bedded Then Wed,"heidi_betts,fiction,2006"
1998,1996,Blackmailed Into Bed,"heidi_betts,fiction,2007"
1999,1997,Tell Me No Lies,"elizabeth_lowell,fiction,2006"